# Base image
FROM node:14.18.1-alpine3.14

# Set the working directory to /app
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the source code to the container
COPY . .

# Set the environment variables
ENV REACT_APP_API_BASE_URL=http://localhost:9081/api

# Build the UI
RUN npm run build

# Set the entry point for the container
CMD ["npm", "start"]
